import localFont from "next/font/local";
import { Merriweather } from "next/font/google";
import Navbar from "@/components/navbar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const merriweather = Merriweather({
  weight: ['400', '700'], // Specify the weights you need
  subsets: ['latin'], // Specify the subsets you need
  variable: '--font-merriweather',
});

const cheltenham = localFont({
  src: "./fonts/cheltenhamNormal.ttf",
  variable: "--font-cheltenham",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cheltenham.variable} antialiased flex flex-col min-h-screen bg-background text-foreground`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
